version: '3.3'

services:
  nginx1:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - "./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - nginx2
      - nginx3
      - memcached1
      - memcached2
      - memcached3
  nginx2:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - "./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - nginx3
      - memcached1
      - memcached2
      - memcached3
  nginx3:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - "./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - memcached1
      - memcached2
      - memcached3
  memcached1:
    image: memcached:latest
    ports:
      - "11211"
  memcached2:
    image: memcached:latest
    ports:
      - "11211"
  memcached3:
    image: memcached:latest
    ports:
      - "11211"
  bench:
    build: ./dockerfiles/benchmarker
    depends_on:
      - nginx1
