version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - "./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf"
  bench:
    build: ./dockerfiles/benchmarker
    depends_on:
      - nginx
