version: '3.3'

services:
  nginx1:
    image: openresty/openresty:alpine
    ports:
      - "80"
    volumes:
      - "./dockerfiles/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    depends_on:
      - nginx2
      - nginx3
      - redis
  nginx2:
    image: openresty/openresty:alpine
    ports:
      - "80"
    volumes:
      - "./dockerfiles/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    depends_on:
      - nginx3
      - redis
  nginx3:
    image: openresty/openresty:alpine
    ports:
      - "80"
    volumes:
      - "./dockerfiles/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379" 
  bench:
    build: ./dockerfiles/benchmarker
    depends_on:
      - nginx1
